name: CI/CD

on:
  push:

env:
  python-version: "3.11"
  POETRY_DYNAMIC_VERSIONING: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}
      - run: pip install pre-commit
      - run: pre-commit run --all-files
  # build-push-package:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ env.python-version }}
  #     - name: Install poetry
  #       run: |
  #         curl -sSL https://install.python-poetry.org | python3 -
  #         echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
  #         poetry self add poetry-dynamic-versioning
  #     - name: Build package
  #       run: |
  #         poetry install --only main
  #         poetry build
  #     - name: Publish package
  #       if: startsWith(github.ref, 'refs/tags/')
  #       run: poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
  build-push-docker:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:$(git describe --tags --always) .
      - name: Push docker image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
